# Generated by Django 4.2.6 on 2025-01-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.TextField(blank=True)),
                ('available_time', models.JSONField(default=dict)),
            ],
        ),
    ]
